import type { Metadata } from 'next'
import Script from 'next/script'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://js.sonikit.com/v1/embed.js?key=68d5ca1a9edd26453cd07cd0"
          type="module"
        />
      </head>
      <body className="bg-black overflow-hidden">
        <div className="sonikit-patch" data-id="68d5d2d99edd26453cd09250"></div>
        {children}
      </body>
    </html>
  )
}
